#!/usr/bin/env bash
# Download the three evaluated NVFP4 checkpoints into the local HF cache, bake
# the YaRN context extension into local Qwen model dirs, and build the seeded
# synthetic RULER corpora used for the headline acceptance/TPOT run.
#
# NOTE ON YARN: the two Qwen checkpoints ship a native 262,144-token context. To
# reach ~1.05M we set a YaRN rope_scaling factor of 4. These are *multimodal*
# configs (text model nested under text_config), and SGLang's runtime json
# override shallow-replaces text_config (dropping num_attention_heads -> engine
# crash), so we bake the edit into a local config.json instead: symlink the HF
# snapshot into $MODELS_DIR/<name>-yarn4 and write a config.json with
# text_config.rope_parameters={rope_type:yarn, factor:4.0,
# original_max_position_embeddings:262144} and max_position_embeddings=1048576.
# run/run_point.sh points q35/q122 at these dirs. Nemotron is native NoPE (no
# rope edit) and is used straight from the HF cache.
set -euo pipefail
cd "$(dirname "$0")/.."
source ./config.env

export HF_HOME="$HF_CACHE"
mkdir -p "$HF_CACHE" "$DATA_DIR/ruler_qa_1m" "$MODELS_DIR"

if ! command -v hf >/dev/null 2>&1 && ! command -v huggingface-cli >/dev/null 2>&1; then
  # Install into the host venv (avoids PEP 668 "externally-managed-environment").
  echo "[02] HF CLI not found; running setup/00_venv.sh to create venv + install ..."
  bash setup/00_venv.sh
  source ./config.env   # re-source to activate the freshly created venv
fi
DL() { if command -v hf >/dev/null 2>&1; then hf download "$1"; else huggingface-cli download "$1"; fi; }

# Some repos may require `huggingface-cli login` (accept model terms first).
echo "[02] downloading checkpoints into $HF_CACHE (this is 100s of GB) ..."
DL "$MODEL_Q35"
DL "$MODEL_Q122"
DL "$MODEL_NEMO"

# Bake YaRN factor 4 into local Qwen model dirs (weights symlinked, config real).
echo "[02] preparing YaRN-extended Qwen model dirs under $MODELS_DIR ..."
python src/prep_yarn_model.py --src "$MODEL_Q35"  --dst "$Q35_LOCAL"  --factor 4.0 --orig 262144
python src/prep_yarn_model.py --src "$MODEL_Q122" --dst "$Q122_LOCAL" --factor 4.0 --orig 262144

# --- headline input corpora (seeded, in-repo RULER generator -> byte-stable) --
# The headline uses SYNTHETIC RULER tasks generated by src/gen_ruler.py: a
# dependency-free, fully-seeded re-implementation of the RULER families (Hsieh et
# al. 2024). They are byte-reproducible on any Python 3.8+, carry no dataset
# license, and need no network -- ideal for an artifact. We ship the generator,
# not the ~40MB jsonl (Git LFS / Release assets do not survive anonymization),
# and verify each build against setup/input_checksums.sha256.
#
# The two headline inputs (Table 1) and the end-to-end marquee task:
#   niah_multiquery_enum : retrieve+list 48 magic numbers (long structured answer)
#   fwe_enum             : list the top-30 most frequent words (aggregation)
#   cwe                  : list the 30 most common words (the paper's marquee task)
# "enum" = the answer-count knob (--niah-queries/--fwe-topk) is cranked so the
# model emits a genuinely long list -> a real decode window at 1M context. The
# harness re-tokenizes and slices `context` to the exact ISL, so the 1150000
# target-token filename is only a nominal size.
RULER_DIR="$DATA_DIR/ruler_qa_1m"
gen_ruler() {  # $1=jsonl name  $2..=extra gen_ruler.py flags
  local out="$RULER_DIR/$1"; shift
  if [ -s "$out" ]; then echo "[02] ruler corpus already present: $out"; return; fi
  echo "[02] building ruler corpus -> $out"
  python src/gen_ruler.py --lengths 1150000 --num-samples 8 --out-dir "$RULER_DIR" "$@"
}
gen_ruler niah_multiquery_enum_1150000.jsonl --tasks niah_multiquery --niah-queries 48 --label enum
gen_ruler fwe_enum_1150000.jsonl             --tasks fwe            --fwe-topk 30      --label enum
gen_ruler cwe_1150000.jsonl                  --tasks cwe            --cwe-common 30

# Determinism check: compare against the reference checksums used for the paper.
# The RULER corpora are deterministic on any Python 3.8+, so a mismatch means the
# generator was edited or a different Python built them -- WARN, don't fail.
echo "[02] verifying input checksums against setup/input_checksums.sha256 ..."
if command -v sha256sum >/dev/null 2>&1; then
  if (cd "$REPRO_ROOT" && sha256sum -c setup/input_checksums.sha256); then
    echo "[02] inputs match the paper reference (byte-identical)."
  else
    echo "[02] WARNING: input checksum mismatch -- your corpora differ from the paper's."
    echo "     Check your Python version / that src/gen_ruler.py is unmodified."
  fi
else
  echo "[02] (sha256sum not found; skipping checksum verification)"
fi

echo "[02] done."
